### PR TITLE
Add docs

### PR DESCRIPTION
**Pull request by abhishalya**
This adds documentation created from Documenter.jl

### CODE REVIEW

**Comment by abhishalya** [comment]
I think we require some more instructions in the make.jl file for the deployment, etc. I would make the changes required asap.

**Comment by logankilpatrick** [comment]
when you run the `make.jl` file, it should create html files.

**Comment by abhishalya** [comment]
It does... We don't have to include the build folder right?

**Comment by abhishalya** [comment]
Just wanted to know if we have to include
```jl
deploydocs(
    repo = "github.com/logankilpatrick/StackOverflow.jl.git",
    target = "build"
)
```

**Comment by logankilpatrick** [comment]
what does that deploy docs do?

**Comment by abhishalya** [comment]
>what does that deploy docs do?

https://juliadocs.github.io/Documenter.jl/dev/lib/public/#Documenter.deploydocs

**Comment by logankilpatrick** [comment]
yes that works for me

**Comment by abhishalya** [comment]
Okay, amending the commit. Is there anything else you want me to add/change?

**Comment by logankilpatrick** [comment]
can you show the outputed index.HTML file?

**Comment by abhishalya** [comment]
http://dpaste.com/3F5YQTQ

image

**Comment by logankilpatrick** [comment]
awesome!

**Comment by logankilpatrick** [comment]
I'm ready to merge if you are.

**Comment by abhishalya** [comment]
Looks ready now

**Pull request merged**
